/*
ESTE ARQUIVO É APENAS PARA TESTES EXECUTADOS VIA TERMINAL
NÃO POSSUI NENHUMA INTERFACE GRÁFICA E PARA CADA AULA DO CURSO,
SERÁ CRIADO UM ARQUIVO .DART COM O NOME DO TEMA ESTUDADO.
*/

main() {
  print("Arquivos para Treinamento do Flutter e Dart");
}
